### PR TITLE
Hologram effect by Benjamin Elder

### PR DESCRIPTION
**Pull request by aguinet**
Copied from https://elder.dev/posts/open-source-virtual-background/

### CODE REVIEW

**Comment by allo-** [comment]
Hi.

I've done the same and had it not committed yet. Can we compare the implementations?
I pushed it to a branch now: https://github.com/allo-/virtual_webcam_background/tree/hologram

I currently see four differences:

- No extra method, but everything in apply
- A short comment for the source and the license.
- An other way to copy the image (I wonder which one is faster)
- Converting the frame to float (and creating a copy)

I am not 100% sure why the converting to float is needed of if it is needed. I think other filters need it, which use an int8 format in between, but addWeighted should return float anyway?

What do you think?
I would at least like to have the license added to the comment, so it is clear that the code can be used even when the blog post may be deleted sometime.

**Comment by allo-** [comment]
I think when your implementation can really avoid converting to `uint8` in the beginning and back to `float` in the end, it is probably faster.

Can you add to your commit:

- A copyright note as in my version, i.e., mentioning the name and license as it is required by the CC-BY license
- Rename the filter to "Hologram" to make the name more clear.
- `np.roll` creates a copy, so you should be able to replace `holo.copy()` by `holo`

I think the method itself does not copy the array, so there is no need to put it into `apply` for more performance.

**Comment by aguinet** [comment]
Hello!

Your implementation looks simpler, I am fine with taking yours and dropping mine :)

**Comment by allo-** [comment]
Implemented using my branch.

**Pull request closed without merging**
